### ISSUE TITLE
Windows 10 angular/cli

### ISSUE THREAD

**Issue by ampgular** [Microsoft/vscode-recipes#19]
Hi and thanks for your contribution!!

After having seen the @tonysneed NgAir I ran and turbocharged my Vs-code for my MAC.

The problem is that the MAC is only 50% of my live, the rest is Windows 10. I tried to follow the same steps and in windows the debug ng-serve command  does not start compiling the App.

Is there a work around or am I doing something wrong(same steps as with MAC and works)??

If you have any hints will be fantastic.

Thanks

**Comment by tonysneed** [comment]
@ampgular I've tried the recipe on Windows, and it works fine. There are a few caveats, however.
- Make sure to install the latest "Current" version of node and npm: <https://nodejs.org>.
- Install the latest version (1.3) of `@angular/cli` globally using npm.
- Add the Chrome Debugger extension for VS Code.
- Paste json from the recipe into launch.json in .vscode.
- Set a breakpoint in an appropriate location.
- Select the appropriate config in the debug pane (serve, test, or e2e).
- Enter `npm start` in the integrated terminal (or npm run test, or npm run e2e).
- Press F5 to start debugging.
- Lastly, make sure you refresh the browser that opens up in order to hit the breakpoint.

Let me know if this helps!

**Comment by tonysneed** [comment]
@ampgular Note, I have update my repo with separate key bindings for Mac and Windows: <https://github.com/tonysneed/vscode-ng>.

**Comment by ampgular** [comment]
Excellent Thaks!!.
It works!! keep up with the great job!
